name: Rust CI Workflow

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system to run on'
        required: false
        type: string
        default: 'ubuntu-latest'
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true

jobs:
  # ----------------------------------------------------------------------------
  # Build Rust Package
  # ----------------------------------------------------------------------------

  # No build step is needed for Rust in Bazel, already happened in main workflow
  
  # ----------------------------------------------------------------------------
  # Test Rust
  # ----------------------------------------------------------------------------

  rust-test:
    name: Test Rust Core
    runs-on: ${{ inputs.os }}
    env:
      CI: true
      BAZELISK_ALLOW_ENVS: Y
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel-${{ runner.os }}
          restore-keys: bazel-${{ runner.os }}

      - name: Test Core
        run: |
          bazel test //core/... --test_output=errors --keep_going

  # ----------------------------------------------------------------------------
  # Publish Rust Crate
  # ----------------------------------------------------------------------------
  rust-publish-crateio:
    name: Publish Rust Core to crates.io
    runs-on: ${{ inputs.os }}
    needs: rust-test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    env:
      CI: true
      BAZELISK_ALLOW_ENVS: Y
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Rust for cargo publish
        uses: dtolnay/rust-toolchain@stable

      - name: Dry-run package build
        working-directory: core
        run: |
          cargo package --allow-dirty

      - name: Publish to crates.io
        working-directory: core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          if [[ -z "${CARGO_REGISTRY_TOKEN}" ]]; then
            echo "‚ùå Missing secret CARGO_REGISTRY_TOKEN"
            exit 1
          fi
          cargo publish --allow-dirty
